"""create equipment and document tables

Revision ID: 0e13321cc446
Revises: 
Create Date: 2026-09-23 19:57:57.488339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e13321cc446'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_versions_file_hash'), 'document_versions', ['file_hash'], unique=True)
    op.create_index(op.f('ix_document_versions_status'), 'document_versions', ['status'], unique=False)
    op.create_table('equipment_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=False),
    sa.Column('model_code', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manufacturer', 'model_code', name='uq_equipment_manufacturer_model')
    )
    op.create_table('document_version_models',
    sa.Column('document_version_id', sa.Integer(), nullable=False),
    sa.Column('equipment_model_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['equipment_model_id'], ['equipment_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_version_id', 'equipment_model_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_version_models')
    op.drop_table('equipment_models')
    op.drop_index(op.f('ix_document_versions_status'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_file_hash'), table_name='document_versions')
    op.drop_table('document_versions')
    # ### end Alembic commands ###
