"""add document content and ingestion tables

Revision ID: 7500a06a1b83
Revises: 0e13321cc446
Create Date: 2026-09-23 20:05:19.479876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7500a06a1b83'
down_revision: Union[str, Sequence[str], None] = '0e13321cc446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_version_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=30), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_assets_asset_type'), 'document_assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_document_assets_document_version_id'), 'document_assets', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_document_assets_sha256'), 'document_assets', ['sha256'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_version_id', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.String(length=30), server_default='parse', nullable=False),
    sa.Column('stage', sa.String(length=50), server_default='queued', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('parser_config_hash', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_jobs_document_version_id'), 'ingestion_jobs', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_idempotency_key'), 'ingestion_jobs', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_ingestion_jobs_input_hash'), 'ingestion_jobs', ['input_hash'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_status'), 'ingestion_jobs', ['status'], unique=False)
    op.create_table('document_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('document_version_id', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.String(length=30), nullable=False),
    sa.Column('section_path', sa.Text(), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('ordinal', sa.Integer(), server_default='0', nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['document_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_blocks_asset_id'), 'document_blocks', ['asset_id'], unique=False)
    op.create_index('ix_document_blocks_document_page', 'document_blocks', ['document_version_id', 'page_start'], unique=False)
    op.create_index('ix_document_blocks_document_type', 'document_blocks', ['document_version_id', 'block_type'], unique=False)
    op.create_index(op.f('ix_document_blocks_document_version_id'), 'document_blocks', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_document_blocks_evidence_id'), 'document_blocks', ['evidence_id'], unique=True)
    op.add_column('document_versions', sa.Column('original_filename', sa.String(length=255), nullable=True))
    op.add_column('document_versions', sa.Column('storage_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_versions', 'storage_path')
    op.drop_column('document_versions', 'original_filename')
    op.drop_index(op.f('ix_document_blocks_evidence_id'), table_name='document_blocks')
    op.drop_index(op.f('ix_document_blocks_document_version_id'), table_name='document_blocks')
    op.drop_index('ix_document_blocks_document_type', table_name='document_blocks')
    op.drop_index('ix_document_blocks_document_page', table_name='document_blocks')
    op.drop_index(op.f('ix_document_blocks_asset_id'), table_name='document_blocks')
    op.drop_table('document_blocks')
    op.drop_index(op.f('ix_ingestion_jobs_status'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_input_hash'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_idempotency_key'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_document_version_id'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index(op.f('ix_document_assets_sha256'), table_name='document_assets')
    op.drop_index(op.f('ix_document_assets_document_version_id'), table_name='document_assets')
    op.drop_index(op.f('ix_document_assets_asset_type'), table_name='document_assets')
    op.drop_table('document_assets')
    # ### end Alembic commands ###
